### ISSUE TITLE
Issue with HTML tags

### ISSUE THREAD

**Issue by alchemist-s** [antoniandre/simple-syntax-highlighter#16]
Hi! This library is great.

I've come across an issue where the highlighting is off for HTML elements that contain a '-'. Attached a preview below:

![image](https://user-images.githubusercontent.com/9383990/129882754-33b9c005-3fc9-424d-bc67-1268e4bdced6.png)

My code looks like this: 
![image](https://user-images.githubusercontent.com/9383990/129882873-c01e69ed-a606-466a-be3e-e70be1b7f38c.png)

**Comment by antoniandre** [comment]
Hi @alchemist-s,

you should use XML as the language for non standard tags. HTML does not have any tag containing `-`.
If it's vue you can also use the html-vue language. 
Hope it helps. :)

**Comment by alchemist-s** [comment]
Hey @antoniandre thank you for the reply! XML works fine for my case (I was using custom elements).

I noticed that its the same case for some of my CSS code as well, if you'd like to take a look:

![image](https://user-images.githubusercontent.com/9383990/130354523-b8ac8c78-3b9f-45bc-b766-a1f58efc71ef.png)

I'm assuming it's probably because CSS properties don't include a number but in my case they're CSS variables.

**Comment by antoniandre** [comment]
Hi @alchemist-s, that's right, thanks for reporting!
I added support for CSS3 variables in version 1.4.9.
https://antoniandre.github.io/simple-syntax-highlighter/#ex--css

Hope it helps! Please reopen if not solved :)
