### ISSUE TITLE
Highlight for dynamic code

### ISSUE THREAD

**Issue by socunanena** [antoniandre/simple-syntax-highlighter#2]
Hi,

First of all, great component and documentation, super easy to use.

But I have one problem, I'm using a code variable that can be dynamically updated, but it's not reflected on your component:
`<ssh-pre language="js" label="Javascript">{{ code }}</ssh-pre>`

Is there any possibility to make it work?

**Comment by antoniandre** [comment]
Hi @socunanena,
Thanks for your feedback. You're right the changes are not watched.
I'll see what I can do and will let you know.

**Comment by antoniandre** [comment]
@socunanena, in version 1.1.0, the highlighter should now react to your variable changes.
Hope it helps.

**Comment by socunanena** [comment]
Perfect! The problem is solved, so fast, thanks!

What I see now is that numbers (`class="number"`) have a strange format, not aligned with the rest of the code. Is it the expected behaviour?

**Comment by antoniandre** [comment]
@socunanena,
I have updated the codebase to have this reactivity on demand, and be default it is not.
Most of the cases don't need reactivity, but you can individually add the `reactive` option to the instances that need it.

```html
<ssh-pre language="js" label="Javascript" reactive>
  // Some reactive Javascript content.
</ssh-pre>
```

Refer to: https://antoniandre.github.io/simple-syntax-highlighter/#options

Regarding why the numbers are not aligned:
- Do you see the numbers of the documentation page aligned correctly?
- which browser and OS is it?
- what is the code?
- do you use an external library that might override the CSS?
- can you show me a screenshot?

**Comment by socunanena** [comment]
Hi @antoniandre,

Regarding the reactivity, it's working even though I don't use the "reactive" attribute in your tag.

And yes, my fault, there's a conflict between your styles and another library I'm using, so don't worry about that.

Thanks a lot for your help and for being so fast! 👌
