### ISSUE TITLE
Can't use the plugin 

### ISSUE THREAD

**Issue by Ju01110101** [antoniandre/simple-syntax-highlighter#22]
If I add the snippet containing `whitespace: 'preserve'` in my `vite.config.js` as instructed on whitespace: 'preserve' I'm getting this error:

`[plugin:vite:vue] At least one <template> or <script> is required in a single file component.`

Here's my `vite.config.js`:

![Screenshot_1](https://github.com/antoniandre/simple-syntax-highlighter/assets/6838902/dd47bbb9-aa61-4097-b9f6-1545ef7bf588)

**Comment by antoniandre** [comment]
Hi @fabricepallaud,
Sorry for delay, well it can still help the next reader.

In order to define the whitespace policy with Vite, this is the markup you need:

```js
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: {
          whitespace: 'preserve'
        }
      }
    })
  ],
  ...
```

Cheers!

**Comment by antoniandre** [comment]
I'll update the outdated docs right away, thanks for pointing it out!
