### ISSUE TITLE
Wrong label in demo page

### ISSUE THREAD

**Issue by yairEO** [antoniandre/simple-syntax-highlighter#4]
![image](https://user-images.githubusercontent.com/845031/86581946-815cf880-bf89-11ea-9246-d27f694bc90f.png)

**Comment by yairEO** [comment]
Ok I get what happened here... nm :)

**Comment by antoniandre** [comment]
Hi @yairEO, 
no problem, I made it clearer in the documentation.
https://antoniandre.github.io/simple-syntax-highlighter
