### ISSUE TITLE
&currency always become ¤cy

### ISSUE THREAD

**Issue by ivebe** [antoniandre/simple-syntax-highlighter#5]
**&curren** always get decoded to ¤

I tried:
1) `&amp;currency` (html entity)
2) `&amp;&#99;urrency` (html entity + html code for letter c)
3) `&#38;currency` (html code)
4) `&#x26;currency` (hex code)

Nothing works.

**Comment by antoniandre** [comment]
Hi @ivebe,
For HTML, you have to write `&amp;amp;currency`.

It's not because of the currency word but because of the `&` being a special character for HTML. So you have to escape it with `&amp;amp;`.

I will add a note about it in the documentation.

Hope it helps.
