### ISSUE TITLE
Break line?

### ISSUE THREAD

**Issue by lorraineS** [antoniandre/simple-syntax-highlighter#7]
When I copy-paste your HTML markup, the rendered code is displayed as one line.

I am not sure I understand why. Do you have an idea ?

Thanks so much.

![review-pre-code](https://user-images.githubusercontent.com/6030502/96430122-14046900-1202-11eb-913a-2c25e1c4264e.jpg)

**Comment by antoniandre** [comment]
Hi @lorraineS, 
Yes, this is explained in the installation section of the documentation: https://antoniandre.github.io/simple-syntax-highlighter/#installation.

Do you use Vue 2 or 3?

- If it is Vue 2, you're covered, just add the code snippet of the section highlighted in blue from the link above.
- In Vue 3, you will not yet be able to have the whitespaces preserved, not until they merge this open PR: https://github.com/vuejs/vue-next/pull/1600, please add a thumb up or comment as well!

Hope it helps.

**Comment by lorraineS** [comment]
I'm using vue3, so i will wait. Thanks

**Comment by antoniandre** [comment]
Closing this issue as the feature is in the vue 3 project.
I am checking the status of the PR pretty much every day, will let you know when they support it. ;)
